runtime: custom
env: flex
instance_class: F1

manual_scaling:
  instances: 1

skip_files:
  - .cicleci/
  - README.md

readiness_check:
  path:               "/healthz"
  check_interval_sec: 30
  timeout_sec:        4
  failure_threshold:  2
  success_threshold:  2

liveness_check:
  path: "/healthz"
  check_interval_sec: 120
  timeout_sec: 6
  failure_threshold: 2
  success_threshold: 2