development:
  dialect: "sqlite3"
  database: "/var/databases/worldlocations_production.sqlite"

test:
  dialect: "sqlite3"
  database: "/tmp/databases/worldlocations_test.sqlite"

production:
  dialect: "sqlite3"
  database: "/var/databases/worldlocations_production.sqlite"
